import { Pool, PoolClient, PoolConfig, QueryResultRow, types } from "pg";
import fs from "fs";
import path from "path";
import { hashPassword, isHashed } from "./password";

// BIGINT columns (task/comment ids) come back as strings by default -> convert to numbers
types.setTypeParser(20, (v) => Number(v));

export type Role = "admin" | "manager" | "team member" | "user";
export const ROLES: Role[] = ["admin", "manager", "team member", "user"];

export interface DbUser {
  id: number;
  name: string;
  email: string;
  password: string;
  role: Role;
}
export type PublicUser = Omit<DbUser, "password">;

const usersSeedFile = path.join(process.cwd(), "users.json");
const tasksSeedFile = path.join(process.cwd(), "tasks.json");

/** Turns DATABASE_URL into a node-postgres config (works for Neon and local Postgres). */
export function buildPoolConfig(raw: string): PoolConfig {
  const url = new URL(raw);
  const mode = url.searchParams.get("sslmode");
  const isLocal = ["localhost", "127.0.0.1", "::1"].includes(url.hostname);
  const useSsl = mode ? mode !== "disable" : !isLocal;
  // node-postgres handles TLS through the `ssl` option, so drop these URL params
  url.searchParams.delete("sslmode");
  url.searchParams.delete("channel_binding");
  return { connectionString: url.toString(), ssl: useSsl ? true : false, max: 5 };
}

const g = globalThis as unknown as { __tmsPool?: Pool; __tmsReady?: Promise<void> };

function getPool(): Pool {
  if (!g.__tmsPool) {
    const raw = process.env.DATABASE_URL;
    if (!raw) throw new Error("DATABASE_URL is not set. Add it to your .env file.");
    const pool = new Pool(buildPoolConfig(raw));
    pool.on("error", (err) => console.error("Postgres pool error:", err));
    g.__tmsPool = pool;
  }
  return g.__tmsPool;
}

const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS tms_meta (
     key   TEXT PRIMARY KEY,
     value TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS tms_users (
     id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name       TEXT NOT NULL,
     email      TEXT NOT NULL,
     password   TEXT NOT NULL,
     role       TEXT NOT NULL DEFAULT 'user'
                CHECK (role IN ('admin','manager','team member','user')),
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tms_users_email_key ON tms_users (lower(email))`,
  // user_id = creator (their tasks are removed with them), assigned_to = assignee (unassigned if removed).
  // due_date is TEXT on purpose: the dashboards store and read plain "YYYY-MM-DD" strings.
  `CREATE TABLE IF NOT EXISTS tms_tasks (
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id     INTEGER REFERENCES tms_users(id) ON DELETE CASCADE,
     assigned_to INTEGER REFERENCES tms_users(id) ON DELETE SET NULL,
     title       TEXT NOT NULL,
     description TEXT,
     due_date    TEXT,
     priority    TEXT,
     category    TEXT,
     status      TEXT NOT NULL DEFAULT 'pending',
     completed   BOOLEAN NOT NULL DEFAULT false,
     attachments TEXT[] NOT NULL DEFAULT '{}',
     created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
   )`,
  `CREATE INDEX IF NOT EXISTS tms_tasks_user_idx ON tms_tasks (user_id)`,
  `CREATE INDEX IF NOT EXISTS tms_tasks_assigned_idx ON tms_tasks (assigned_to)`,
  // Task discussion / communication
  `CREATE TABLE IF NOT EXISTS tms_comments (
     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id    BIGINT NOT NULL REFERENCES tms_tasks(id) ON DELETE CASCADE,
     user_id    INTEGER REFERENCES tms_users(id) ON DELETE SET NULL,
     manager_id INTEGER REFERENCES tms_users(id) ON DELETE SET NULL,
     message    TEXT NOT NULL,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   )`,
  `CREATE INDEX IF NOT EXISTS tms_comments_task_idx ON tms_comments (task_id)`,
  // Add manager_id to existing tables FIRST (idempotent), then create the index
  `ALTER TABLE tms_comments ADD COLUMN IF NOT EXISTS manager_id INTEGER REFERENCES tms_users(id) ON DELETE SET NULL`,
  `CREATE INDEX IF NOT EXISTS tms_comments_manager_idx ON tms_comments (manager_id)`,
  // Admin-managed lists
  `CREATE TABLE IF NOT EXISTS tms_categories (
     id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name TEXT NOT NULL
   )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tms_categories_name_key ON tms_categories (lower(name))`,
  `CREATE TABLE IF NOT EXISTS tms_labels (
     id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name TEXT NOT NULL
   )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tms_labels_name_key ON tms_labels (lower(name))`,
];

const readJson = (file: string): any | null => {
  if (!fs.existsSync(file)) return null;
  try {
    return JSON.parse(fs.readFileSync(file, "utf-8") || "null");
  } catch {
    return null;
  }
};

const resetSequence = (c: PoolClient, table: string) =>
  c.query(
    `SELECT setval(pg_get_serial_sequence('${table}','id'),
                   (SELECT COALESCE(MAX(id), 0) + 1 FROM ${table}), false)`
  );

/** One-time import of users.json (only if never imported and the table is empty). */
async function importUsers(c: PoolClient) {
  const done = await c.query(`SELECT 1 FROM tms_meta WHERE key = 'users_imported'`);
  if (done.rowCount) return;

  const count = await c.query(`SELECT count(*)::int AS n FROM tms_users`);
  const seed = readJson(usersSeedFile);
  if (count.rows[0].n === 0 && Array.isArray(seed)) {
    for (const u of seed) {
      const role: Role = ROLES.includes(u.role) ? u.role : "user";
      const pw = isHashed(String(u.password)) ? String(u.password) : await hashPassword(String(u.password));
      // keep the original ids: tasks refer to users by id
      await c.query(
        `INSERT INTO tms_users (id, name, email, password, role)
         VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING`,
        [Number(u.id), u.name, u.email, pw, role]
      );
    }
    await resetSequence(c, "tms_users");
  }
  await c.query(`INSERT INTO tms_meta (key, value) VALUES ('users_imported', 'yes')`);
}

/** One-time import of tasks.json incl. their comments. Never re-imports after deletions. */
async function importTasks(c: PoolClient) {
  const done = await c.query(`SELECT 1 FROM tms_meta WHERE key = 'tasks_imported'`);
  if (done.rowCount) return;

  const count = await c.query(`SELECT count(*)::int AS n FROM tms_tasks`);
  const seed = readJson(tasksSeedFile);
  const tasks: any[] = Array.isArray(seed?.tasks) ? seed.tasks : [];

  if (count.rows[0].n === 0) {
    for (const t of tasks) {
      const completed = !!t.completed;
      // user references that no longer exist become NULL instead of failing the import
      await c.query(
        `INSERT INTO tms_tasks
           (id, user_id, assigned_to, title, description, due_date, priority, category, status, completed, attachments)
         VALUES ($1,
                 (SELECT id FROM tms_users WHERE id = $2),
                 (SELECT id FROM tms_users WHERE id = $3),
                 $4, $5, $6, $7, $8, $9, $10, $11)
         ON CONFLICT DO NOTHING`,
        [
          Number(t.id),
          t.userId ?? null,
          t.assignedTo ?? null,
          String(t.title ?? ""),
          t.description ?? null,
          t.dueDate ?? null,
          t.priority ?? null,
          t.category ?? null,
          t.status ?? (completed ? "completed" : "pending"),
          completed,
          Array.isArray(t.attachments) ? t.attachments.map(String) : [],
        ]
      );
      for (const cm of Array.isArray(t.comments) ? t.comments : []) {
        const when = new Date(cm.createdAt);
        await c.query(
          `INSERT INTO tms_comments (id, task_id, user_id, message, created_at)
           VALUES ($1, $2, (SELECT id FROM tms_users WHERE id = $3), $4, $5)
           ON CONFLICT DO NOTHING`,
          [
            Number(cm.id),
            Number(t.id),
            cm.userId ?? null,
            String(cm.message ?? ""),
            (isNaN(when.getTime()) ? new Date() : when).toISOString(),
          ]
        );
      }
    }
    await resetSequence(c, "tms_tasks");
    await resetSequence(c, "tms_comments");
  }
  await c.query(`INSERT INTO tms_meta (key, value) VALUES ('tasks_imported', 'yes')`);
}

/** Creates all tables on first use and imports the old JSON files once. Runs in one transaction. */
async function init(pool: Pool) {
  const c = await pool.connect();
  try {
    await c.query("BEGIN");
    await c.query("SELECT pg_advisory_xact_lock(727001)"); // serialise concurrent first requests
    for (const sql of SCHEMA) await c.query(sql);
    await importUsers(c);
    await importTasks(c);
    await c.query("COMMIT");
  } catch (err) {
    await c.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    c.release();
  }
}

async function ready(): Promise<Pool> {
  const pool = getPool();
  if (!g.__tmsReady) {
    g.__tmsReady = init(pool).catch((err) => {
      g.__tmsReady = undefined; // retry on the next request
      throw err;
    });
  }
  await g.__tmsReady;

  // Run lightweight column migrations on every process start (idempotent, fast).
  // This catches cases where g.__tmsReady was already set before a schema change.
  if (!(g as any).__tmsMigrated) {
    (g as any).__tmsMigrated = pool.query(
      `ALTER TABLE tms_comments ADD COLUMN IF NOT EXISTS manager_id INTEGER REFERENCES tms_users(id) ON DELETE SET NULL`
    ).catch((err) => {
      (g as any).__tmsMigrated = undefined;
      console.warn("Migration warning (manager_id):", err.message);
    });
  }
  await (g as any).__tmsMigrated;

  return pool;
}

export async function query<T extends QueryResultRow = any>(text: string, params: any[] = []) {
  const pool = await ready();
  return pool.query<T>(text, params);
}

export async function withTransaction<T>(fn: (c: PoolClient) => Promise<T>): Promise<T> {
  const pool = await ready();
  const c = await pool.connect();
  try {
    await c.query("BEGIN");
    const result = await fn(c);
    await c.query("COMMIT");
    return result;
  } catch (err) {
    await c.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    c.release();
  }
}

export const isUniqueViolation = (err: any) => err?.code === "23505";
export const isForeignKeyViolation = (err: any) => err?.code === "23503";

// ---------------------------------------------------------------- users

const PUBLIC_COLS = "id, name, email, role";

export async function listUsers(): Promise<PublicUser[]> {
  const { rows } = await query(`SELECT ${PUBLIC_COLS} FROM tms_users ORDER BY id`);
  return rows;
}

export async function findUserByEmail(email: string): Promise<DbUser | null> {
  const { rows } = await query(
    `SELECT ${PUBLIC_COLS}, password FROM tms_users WHERE lower(email) = lower($1)`,
    [email]
  );
  return rows[0] ?? null;
}

export async function findUserById(id: number): Promise<DbUser | null> {
  const { rows } = await query(
    `SELECT ${PUBLIC_COLS}, password FROM tms_users WHERE id = $1`,
    [id]
  );
  return rows[0] ?? null;
}

/** New accounts are always created with the default "user" role. */
export async function createUser(name: string, email: string, passwordHash: string): Promise<PublicUser> {
  const { rows } = await query(
    `INSERT INTO tms_users (name, email, password, role)
     VALUES ($1, $2, $3, 'user') RETURNING ${PUBLIC_COLS}`,
    [name, email, passwordHash]
  );
  return rows[0];
}

export async function updateUserRole(id: number, role: Role): Promise<PublicUser | null> {
  const { rows } = await query(
    `UPDATE tms_users SET role = $2 WHERE id = $1 RETURNING ${PUBLIC_COLS}`,
    [id, role]
  );
  return rows[0] ?? null;
}

export async function updateUserPassword(id: number, passwordHash: string) {
  await query(`UPDATE tms_users SET password = $2 WHERE id = $1`, [id, passwordHash]);
}

/** Deleting a user also removes tasks they created (and those tasks' comments) and unassigns
 *  tasks assigned to them. Their comments on other people's tasks are kept, with no author. */
export async function deleteUser(id: number): Promise<boolean> {
  const res = await query(`DELETE FROM tms_users WHERE id = $1`, [id]);
  return (res.rowCount ?? 0) > 0;
}
